version: "3.9"

services:
  db:
    image: postgres
    container_name: investment-postgres-db
    restart: always

    environment:
      POSTGRES_DB: investment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123

    volumes:
      - investment_postgres_data:/var/lib/postgresql/data

    ports:
      - 8015:5432

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: investment-fastapi-backend
    restart: always
    volumes:
      - ./server:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - server/.env

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: investment-react-frontend
    restart: always
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  investment_postgres_data:
