"""Updated investment and mutual fund tables

Revision ID: 798404416534
Revises: 
Create Date: 2025-03-16 15:31:39.074925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '798404416534'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investments', sa.Column('nav_at_investment', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.drop_constraint('investments_user_id_fkey', 'investments', type_='foreignkey')
    op.drop_column('investments', 'user_id')
    op.drop_column('mutual_funds', 'nav_at_investment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mutual_funds', sa.Column('nav_at_investment', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('investments', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('investments_user_id_fkey', 'investments', 'users', ['user_id'], ['id'])
    op.drop_column('investments', 'nav_at_investment')
    # ### end Alembic commands ###
