version: "3.9"

services:
  db:
    image: postgres
    container_name: investment-postgres-db
    restart: always

    environment:
      POSTGRES_DB: investment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - 8015:5432

volumes:
  postgres_data:
